[workspace]
resolver = "2"
members = [
    "rscx",
    "rscx-macros",
    "benches",
]
exclude = [
    "website",
]

[workspace.package]
version = "0.1.12"

[workspace.dependencies]
rscx = { path = "./rscx", version = "0.1.12" }
rscx-macros = { path = "./rscx-macros", version = "0.1.12" }
